server:
  port: 8080

spring:
  application:
    name: courier-new
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ?? ?? campus_courier ??????????
    url: jdbc:mysql://localhost:3306/campus_courier?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    # ??? ??? DBeaver ??????????
    password: "123456"

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl